@startuml
    !theme crt-amber

:Admin: -> (Criar categoria)
:Admin: -> (Atualizar categoria)
:Admin: -> (Excluir categoria)
:Admin: -> (Consultar uma categoria)
:Admin: -> (Consultar em categorias)


@enduml

